### PR TITLE
Ex 2 Task A - Implemented iadd

### PR DESCRIPTION
**Pull request by SyedMustafaAhmad**
Ex 2 Task A - Implemented iadd

### CODE REVIEW

**Comment by SyedMustafaAhmad** [comment]
I approve it because I said so.

**Comment by SyedMustafaAhmad** [comment]
I can't approve it!!!!

**Review by sashansamarajeewa — APPROVED** [review]
Looks good!

**Comment by sashansamarajeewa** [comment]
Approved

**Pull request merged**
