### PR TITLE
Ex 2 Task B - def contain tolerance function definition

### PR DESCRIPTION
**Pull request by SyedMustafaAhmad**
Ex 2 Task B - def contain tolerance function definition

### CODE REVIEW

**Comment by SyedMustafaAhmad** [comment]
def _is_in_interval(self, value: float, low: float, high: float, tolerance: float = 0.0) -> bool:
        return (low - tolerance) <= value <= (high + tolerance)

**Comment by SyedMustafaAhmad** [comment]
def contains(self, point: Point2D, tolerance: float = 0.0) -> bool:
        return self._is_in_interval(point.x, self._lower_left.x, self._lower_left.x + self._dx, tolerance) \
            and self._is_in_interval(point.y, self._lower_left.y, self._lower_left.y + self._dy, tolerance)

**Review by sashansamarajeewa — APPROVED** [review]
Looks Good!

**Comment by sashansamarajeewa** [comment]
Approved!

**Pull request merged**
